### ISSUE TITLE
No Content in Trending and New Channels

### ISSUE THREAD

**Issue by edje42** [spknetwork/3Speak-app#10]
Content is missing in Trending and New channels, while content in my Home channel is available and updated as new content from my followers list is published. IPFS seems to be working, number of peers ranges between a few 100 to over 500. Have a IPFS plugin in my webbrowser. Not sure anymore if this was part if the initial 3Speak App deployment, or I already had this in my browser.

My environment:
- MacBook with Catalina OSX
- 3Speak App version .12
- IPFS Brave Plugin v0.7.0
- Browser: Brave (latest version: Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (x86_64))

**Comment by unklebonehead** [comment]
This is still the same in Appimage on v0.14 as well

**Comment by igormuba** [comment]
Fixed the missing data on PR
https://github.com/spknetwork/3Speak-app/pull/27
